---
## epel location vars
epel_repo_url: "https://archives.fedoraproject.org/pub/archive/epel/7.9/x86_64/Packages/e/epel-release-7-12.noarch.rpm"
epel_repo_gpg_key_url: "https://archives.fedoraproject.org/pub/archive/epel/RPM-GPG-KEY-EPEL"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"
epel_repo_disable: false

## Add any additional packages
additional_packages:
  - nfs-utils
  - iscsi-initiator-utils
  - device-mapper-multipath
  - sg3_utils
  - git
  - https://s3.{{ region| default("eu-west-2") }}.amazonaws.com/amazon-ssm-{{ region| default("eu-west-2") }}/latest/linux_amd64/amazon-ssm-agent.rpm
  - libselinux-python
  - libsemanage-python
  - policycoreutils-python
  - screen
  - logrotate
  - chrony

pip_install_packages:
  - name: pip
    state: latest
  - name: ansible
    version: "2.10.6"
  - name: j2cli
    umask: "0022"

clamav_mirror: http://clamav-mirror.sharedservices.aws.internal

selinux_policies:
  - antivirus_can_scan_system

## CloudWatch Agent Variables
cwa_conf_json_file_content: "{{ lookup('file', 'files/cloudwatch-config.json') }}"

## CIS Hardening Variables
rhel7cis_time_synchronization: chrony
rhel7cis_time_synchronization_servers: ["169.254.169.123"] #Default VPC source
rhel7cis_squid_server: true
rhel7cis_firewall: "iptables"
#Disable rsyslog/syslog-ng, using cloudwatch
rhel7cis_rule_4_2_3: false
rhel7cis_rule_4_2_1_1: false
rhel7cis_rule_4_2_1_2: false
rhel7cis_rule_4_2_1_3: false
rhel7cis_rule_4_2_1_4: false
rhel7cis_rule_4_2_1_5: false
rhel7cis_rule_4_2_2_1: false
rhel7cis_rule_4_2_2_2: false
rhel7cis_rule_4_2_2_3: false
rhel7cis_rule_4_2_2_4: false
rhel7cis_rule_4_2_2_5: false
rhel7cis_rule_4_3: false
#Disable GRUB tasks
rhel7cis_rule_1_4_2: false
rhel7cis_rule_1_6_1_1: false
rhel7cis_rule_4_1_3: false
#Disable Firewall Tasks, we manage this in app deploy
rhel7cis_rule_3_6_1: false
rhel7cis_rule_3_6_2: false
rhel7cis_rule_3_6_3: false
rhel7cis_rule_3_6_4: false
rhel7cis_rule_3_6_5: false
rhel7cis_rule_5_4_4: false
rhel7cis_rule_5_4_5: false
# Setup hosts.allow entries
rhel7cis_host_allow:
  - "127.0.0.1"
  - "10.0.0.0/255.0.0.0"
  - "172.16.0.0/255.240.0.0"
  - "192.168.0.0/255.255.0.0"
